name: gsasacademy
description: A new Flutter project.

version: 1.0.4+4

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.4+2
  firebase_messaging: ^6.0.13
  firebase_storage: ^3.1.5
  flutter_icons: ^1.0.0+1
  shared_preferences: ^0.5.6+3
  progress_dialog: ^1.2.1
  image_picker: ^0.6.4
  firebase_auth: ^0.15.5+3
  fluttertoast: ^4.0.1
  firebase_core: ^0.4.4+3
  provider: ^4.0.5
  cached_network_image: ^2.1.0+1
  advance_pdf_viewer: ^1.1.6
  video_player: ^0.10.8+1
  chewie: ^0.9.10
  photo_view: ^0.9.2
  url_launcher: ^5.4.2
  file_picker: ^1.6.3+2
  connectivity: ^0.4.8+2
  http: ^0.12.0+4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: asset/fonts/OpenSans-Regular.ttf
        - asset: asset/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: asset/fonts/OpenSans-Bold.ttf
          weight: 700
